version: '3'
services:
  mysql:
    image: mysql:5
    container_name: wms-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1
  redis:
    image: redis:latest
    command: redis-server --requirepass qwerqwer123 --port 6379
    container_name: wms-redis
    hostname: docker-redis
    labels:
      - "name=redis"
      - "mode=standalone"
    volumes:
      - $HOME/redis_data:/data
    ports:
      - "6379:6379"
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092